[package]
name = "sanctum"
version = "0.1.0"
edition = "2024"

[dependencies]
audiotags = "0.5.0"
eframe = "0.32.3"
egui = "0.32.3"
env_logger = "0.11.8"
lofty = "0.22.4"
rand = "0.9.2"
rodio = "0.21.1"
serde = "1.0.228"
serde_json = "1.0.145"
